Tim/sms prov
TankerHQ/identity-php pull request #7
Opened 2021-06-23 07:35 UTC by tux3

2021-06-23 07:53 UTC, theodelrieu commented on tests/Tanker/Identity/IdentityTest.php
> +            create_provisional_identity("NOT BASE64", 'email', self::USER_ID);
Single or double quotes, pick one!

2021-06-23 08:15 UTC, JMounier requested changes

2021-06-23 08:15 UTC, JMounier commented on src/Tanker/Identity/identity.php
> +        $pub_id_json["value"] = Internal\tanker_hash_provisional_identity_value($id_json["value"]);
```suggestion

            $pub_id_json["value"] = Internal\tanker_hash_provisional_identity_value($id_json["value"]);
        else if $id_json["target"] === "phone_number"
            salt = sodium_crypto_generichash($id_json["private_signature_key"], '', TANKER_BLOCK_HASH_SIZE)
            $pub_id_json["value"] = Internal\tanker_hash_provisional_identity_value(salt + $id_json["value"])
```

2021-06-23 12:13 UTC, tux3 commented on src/Tanker/Identity/identity.php
> +        $pub_id_json["value"] = Internal\tanker_hash_provisional_identity_value($id_json["value"]);
Fixed, I added a `tanker_hash_provisional_identity_value` with the salt, and a `tanker_hash_provisional_identity_email` without. Thanks

2021-06-23 12:18 UTC, tux3 commented on tests/Tanker/Identity/IdentityTest.php
> +            create_provisional_identity("NOT BASE64", 'email', self::USER_ID);
Thank you, fixed. Single quotes are slightly better, so switching to them everywhere.

2021-06-23 13:29 UTC, JMounier commented on src/Tanker/Identity/internal.php
> +    $hash_salt = sodium_crypto_generichash($private_signature_key, '', TANKER_BLOCK_HASH_SIZE);
Is the `private_signature_key` a base64 string? I don't think we decided which format to use before hashing

2021-06-23 13:42 UTC, JMounier approved these changes

2021-06-23 14:05 UTC, tux3 commented on src/Tanker/Identity/internal.php
> +    $hash_salt = sodium_crypto_generichash($private_signature_key, '', TANKER_BLOCK_HASH_SIZE);
Yeah, I hashed it in string form since that's its "natural" type in the JSON identity, so we save a base64 decode for most (but not all!) SDKs

But that was unspecified, so I'd be happy with either choice =)

2021-06-25 08:18 UTC, JMounier commented on src/Tanker/Identity/internal.php
> +    $hash_salt = sodium_crypto_generichash($private_signature_key, '', TANKER_BLOCK_HASH_SIZE);
Agreed. But we should choose the same salt format for both permanent users and provisional with phone.
For verification methods, we are currently using `hash(userSecret)` where `userSecret` is not in b64.

2021-06-25 08:36 UTC, theodelrieu commented on src/Tanker/Identity/internal.php
> +    $hash_salt = sodium_crypto_generichash($private_signature_key, '', TANKER_BLOCK_HASH_SIZE);
Always binary, always.

2021-06-25 08:58 UTC, tux3 commented on src/Tanker/Identity/internal.php
> +    $hash_salt = sodium_crypto_generichash($private_signature_key, '', TANKER_BLOCK_HASH_SIZE);
Done

2021-06-28 12:51 UTC, theodelrieu approved these changes

2021-06-29 17:00 UTC, JMounier approved these changes

2021-07-02 08:33 UTC, merged